package io.ethertale.olympiaelkridgeuniversity.schools.model;

public enum MainStudyBranches {
//    LAW - Helena Drake College of Jurisprudence
    ENVIRONMENTAL_AND_CLIMATE,
    CYBER_AND_DIGITAL_PRIVACY,
    INTERNATIONAL_HUMAN_RIGHTS,
    BIOETHICS_AND_MEDICAL_REGULATION,
    ENERGY_LAND_AND_RESOURCE,
//    COMPUTER SCIENCE - Cascadian Institute of Computing
    ARTIFICIAL_INTELLIGENCE_AND_MACHINE_LEARNING,
    QUANTUM_COMPUTING_AND_ALGORITHMS,
    HUMAN_COMPUTER_INTERACTION,
    COMPUTATIONAL_BIOLOGY_AND_GENOMICS,
    CYBERSECURITY_AND_PRIVACY,
    GREEN_COMPUTING_AND_SUSTAINABLE_ARCHITECTURE,
//    MEDICINE - Elk Ridge School of Medicine
    ROBOTIC_MEDICINE,
    MENTAL_AND_BEHAVIOURAL_HEALTH_SCIENCES,
    MEDICAL_AI_AND_DIAGNOSTIC_IMAGING,
//    ENGINEERING - Franklin D. Marlowe School of Engineering
    SOFTWARE_ENGINEERING_AND_EMBEDDED_SYSTEMS,
    HARDWARE_AND_MICROELECTRONIC_ENGINEERING,
    RENEWABLE_ENERGY_ENGINEERING,
    CIVIL_INFRASTRUCTURE_AND_SMART_CITIES,
    BIOMATERIALS_AND_MEDICAL_DEVICE_ENGINEERING,
    WATER_SYSTEMS_AND_RECLAMATION_ENGINEERING,
//    QUANTUM PHYSICS - Luthien Advanced Physics Academy
    QUANTUM_FIELD_THEORY_AND_PARTICLE_DYNAMICS,
    ASTROPHYSICS_AND_COSMOLOGICAL_SIMULATION,
    QUANTUM_OPTICS_AND_PHOTONIC_SYSTEMS,
    QUANTUM_THERMODYNAMICS_AND_ENERGY_TRANSFER,
    DARK_MATTER_AND_EXOTIC_PARTICLES_RESEARCH,
    MATHEMATICAL_PHYSICS_AND_SIMULATION_ARCHITECTURE
}
